   FROM eclipse-temurin:17-jdk-alpine
   EXPOSE 8080
   ARG JAR_FILE=target/*.jar
   COPY ${JAR_FILE} project2-0.0.1-SNAPSHOT.jar
     
   RUN apk add --no-cache msttcorefonts-installer fontconfig
   RUN update-ms-fonts
 
   ENTRYPOINT ["java","-jar","/project2-0.0.1-SNAPSHOT.jar"]